name: Push on Master jobs

on:
  push:
    branches: [ master ]

jobs:
  automaticpublish:
    name: Automatic Mod Browser Publish Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
       
      # Mod Browser integration
      - uses: JavidPack/tModLoaderPublishIntegration@master
        with:
          STEAMID64: ${{secrets.STEAMID64}}
          MODBROWSERPASSPHRASE: ${{secrets.MODBROWSERPASSPHRASE}}
          MODNAME: HEROsMod
       
      - uses: actions/upload-artifact@v2
        with:
          name: .tmod file
          path: ~/tModLoader/ModLoader/Mods/HEROsMod.tmod
